USE [master]
GO
/****** Object:  Database [SUPRIMEDICO]    Script Date: 16/11/2019 18:21:54 ******/
CREATE DATABASE [SUPRIMEDICO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUPRIMEDICO', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SUPRIMEDICO.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SUPRIMEDICO_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SUPRIMEDICO_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SUPRIMEDICO] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SUPRIMEDICO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SUPRIMEDICO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET ARITHABORT OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SUPRIMEDICO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SUPRIMEDICO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SUPRIMEDICO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SUPRIMEDICO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SUPRIMEDICO] SET  MULTI_USER 
GO
ALTER DATABASE [SUPRIMEDICO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SUPRIMEDICO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SUPRIMEDICO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SUPRIMEDICO] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SUPRIMEDICO] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SUPRIMEDICO]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[CLI_CPF] [varchar](15) NOT NULL,
	[CLI_PRIMNOME] [varchar](100) NOT NULL,
	[CLI_ULTNOME] [varchar](100) NOT NULL,
	[CLI_DATANASC] [date] NOT NULL,
	[CLI_EMAIL] [varchar](50) NOT NULL,
	[CLI_ENDERECO] [varchar](100) NOT NULL,
	[CLI_BAIRRO] [varchar](100) NOT NULL,
	[CLI_CIDADE] [varchar](100) NOT NULL,
	[CLI_ESTADO] [char](2) NOT NULL,
	[CLI_TELEFONE] [numeric](18, 0) NOT NULL,
	[CLI_SEXO] [char](1) NULL,
	[CLI_CASANUMERO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CLI_CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FUNCIONARIOS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FUNCIONARIOS](
	[FUNC_CPF] [varchar](15) NOT NULL,
	[SET_ID] [int] NOT NULL,
	[FUNC_NOME] [varchar](100) NOT NULL,
	[FUNC_DATANASC] [date] NOT NULL,
	[FUNC_EMAIL] [varchar](50) NOT NULL,
	[FUNC_ENDERECO] [varchar](100) NOT NULL,
	[FUNC_BAIRRO] [varchar](100) NOT NULL,
	[FUNC_CIDADE] [varchar](100) NOT NULL,
	[FUNC_ESTADO] [char](2) NOT NULL,
	[FUNC_TELEFONE] [numeric](18, 0) NOT NULL,
	[FUNC_SALARIO] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FUNC_CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGIN]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGIN](
	[LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[FUNC_CPF] [varchar](15) NOT NULL,
	[LOG_USUARIO] [varchar](50) NOT NULL,
	[LOG_SENHA] [char](6) NOT NULL,
	[LOG_DATACADASTRO] [date] NULL,
	[LOG_PRIVILEGIO] [varchar](50) NOT NULL,
	[LOG_ATUALIZADOEM] [date] NULL,
 CONSTRAINT [PK__LOGIN__4364C882A0DF0FE9] PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PECAS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PECAS](
	[PEC_ID] [int] IDENTITY(1,1) NOT NULL,
	[PEC_NOME] [varchar](100) NOT NULL,
	[PEC_FABRICANTE] [varchar](100) NOT NULL,
	[PEC_QUANTIDADE] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK__PEÇAS__6814620B3DA5DB07] PRIMARY KEY CLUSTERED 
(
	[PEC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUTOS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUTOS](
	[PROD_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROD_NOME] [varchar](100) NOT NULL,
	[PROD_CATEGORIA] [varchar](100) NOT NULL,
	[PROD_DESCRICAO] [varchar](100) NULL,
	[PROD_ESTOQUE] [char](8) NOT NULL,
	[PROD_VLUNIT] [money] NULL,
	[PROD_VFINAL] [int] NULL,
 CONSTRAINT [PK__PRODUTOS__B3271E1161C74F67] PRIMARY KEY CLUSTERED 
(
	[PROD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUTOS_PECAS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUTOS_PECAS](
	[PROD_ID] [int] NULL,
	[PEC_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SETORES]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SETORES](
	[SET_ID] [int] IDENTITY(1,1) NOT NULL,
	[SET_NOME] [varchar](100) NOT NULL,
 CONSTRAINT [PK__SETORES__7D7B0FB5D55D364D] PRIMARY KEY CLUSTERED 
(
	[SET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENDAS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDAS](
	[VEN_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLI_CPF] [varchar](15) NULL,
	[VEND_ID] [int] NULL,
	[VEN_DTEMISSAO] [date] NULL,
	[VEN_VALOR] [money] NULL,
	[VEN_DESCONTO] [money] NULL,
	[VEN_VALORPAGO] [money] NULL,
 CONSTRAINT [PK__VENDAS__6E8A697D4E342EC4] PRIMARY KEY CLUSTERED 
(
	[VEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENDAS_ITENS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDAS_ITENS](
	[VENDA_ITENS_ID] [int] IDENTITY(1,1) NOT NULL,
	[VEN_ID] [int] NULL,
	[PROD_ID] [int] NULL,
	[VENDA_ITENS_QTO] [int] NULL,
	[VENDA_ITENS_VLUNIT] [money] NULL,
	[VENDA_ITENS_TOTAL] [money] NULL,
 CONSTRAINT [PK_VENDAS_ITENS] PRIMARY KEY CLUSTERED 
(
	[VENDA_ITENS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENDEDORES]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDEDORES](
	[VEND_ID] [int] IDENTITY(1,1) NOT NULL,
	[FUNC_CPF] [varchar](15) NOT NULL,
	[VEND_COMISSAO] [float] NOT NULL,
 CONSTRAINT [PK__VENDEDOR__FA0E1EA9B566A72E] PRIMARY KEY CLUSTERED 
(
	[VEND_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VISITAS]    Script Date: 16/11/2019 18:21:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VISITAS](
	[VIS_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLI_CPF] [varchar](15) NULL,
	[VEND_ID] [int] NOT NULL,
	[VIS_DATA] [date] NOT NULL,
	[VIS_HORA] [time](7) NOT NULL,
	[VIS_DESCRICAO] [varchar](200) NULL,
 CONSTRAINT [PK__VISITAS__7AC97FC9B3FA6F13] PRIMARY KEY CLUSTERED 
(
	[VIS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FUNCIONARIOS]  WITH CHECK ADD  CONSTRAINT [FK_SETORES_FUNC] FOREIGN KEY([SET_ID])
REFERENCES [dbo].[SETORES] ([SET_ID])
GO
ALTER TABLE [dbo].[FUNCIONARIOS] CHECK CONSTRAINT [FK_SETORES_FUNC]
GO
ALTER TABLE [dbo].[LOGIN]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONARIOS_LOGIN_FUNC_CPF] FOREIGN KEY([FUNC_CPF])
REFERENCES [dbo].[FUNCIONARIOS] ([FUNC_CPF])
GO
ALTER TABLE [dbo].[LOGIN] CHECK CONSTRAINT [FK_FUNCIONARIOS_LOGIN_FUNC_CPF]
GO
ALTER TABLE [dbo].[VENDAS]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTES_VENDAS_CLI_CPF] FOREIGN KEY([CLI_CPF])
REFERENCES [dbo].[CLIENTES] ([CLI_CPF])
GO
ALTER TABLE [dbo].[VENDAS] CHECK CONSTRAINT [FK_CLIENTES_VENDAS_CLI_CPF]
GO
ALTER TABLE [dbo].[VENDAS]  WITH CHECK ADD  CONSTRAINT [FK_VENDEDORES_VENDAS_VEND_ID] FOREIGN KEY([VEND_ID])
REFERENCES [dbo].[VENDEDORES] ([VEND_ID])
GO
ALTER TABLE [dbo].[VENDAS] CHECK CONSTRAINT [FK_VENDEDORES_VENDAS_VEND_ID]
GO
ALTER TABLE [dbo].[VENDAS_ITENS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTOS_VENDAS_ITENS] FOREIGN KEY([PROD_ID])
REFERENCES [dbo].[PRODUTOS] ([PROD_ID])
GO
ALTER TABLE [dbo].[VENDAS_ITENS] CHECK CONSTRAINT [FK_PRODUTOS_VENDAS_ITENS]
GO
ALTER TABLE [dbo].[VENDAS_ITENS]  WITH CHECK ADD  CONSTRAINT [FK_VENDAS_VENDAS_ITENS_VEN_ID] FOREIGN KEY([VEN_ID])
REFERENCES [dbo].[VENDAS] ([VEN_ID])
GO
ALTER TABLE [dbo].[VENDAS_ITENS] CHECK CONSTRAINT [FK_VENDAS_VENDAS_ITENS_VEN_ID]
GO
ALTER TABLE [dbo].[VENDEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONARIOS_VENDEDORES_FUNC_CPF] FOREIGN KEY([FUNC_CPF])
REFERENCES [dbo].[FUNCIONARIOS] ([FUNC_CPF])
GO
ALTER TABLE [dbo].[VENDEDORES] CHECK CONSTRAINT [FK_FUNCIONARIOS_VENDEDORES_FUNC_CPF]
GO
ALTER TABLE [dbo].[VISITAS]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTES_VISITAS_CLI_CPF] FOREIGN KEY([CLI_CPF])
REFERENCES [dbo].[CLIENTES] ([CLI_CPF])
GO
ALTER TABLE [dbo].[VISITAS] CHECK CONSTRAINT [FK_CLIENTES_VISITAS_CLI_CPF]
GO
ALTER TABLE [dbo].[VISITAS]  WITH CHECK ADD  CONSTRAINT [FK_VENDEDORES_VISITAS_VEND_ID] FOREIGN KEY([VEND_ID])
REFERENCES [dbo].[VENDEDORES] ([VEND_ID])
GO
ALTER TABLE [dbo].[VISITAS] CHECK CONSTRAINT [FK_VENDEDORES_VISITAS_VEND_ID]
GO
USE [master]
GO
ALTER DATABASE [SUPRIMEDICO] SET  READ_WRITE 
GO

/* Pessoa add aqui é totalmente fake */

INSERT INTO [dbo].[SETORES]
           ([SET_NOME])
     VALUES
           ('ADMISTRADOR')
GO

INSERT INTO [dbo].[FUNCIONARIOS]
           ([FUNC_CPF]
           ,[SET_ID]
           ,[FUNC_NOME]
           ,[FUNC_DATANASC]
           ,[FUNC_EMAIL]
           ,[FUNC_ENDERECO]
           ,[FUNC_BAIRRO]
           ,[FUNC_CIDADE]
           ,[FUNC_ESTADO]
           ,[FUNC_TELEFONE]
           ,[FUNC_SALARIO])
     VALUES
           ('479.458.138-60','1','Thiago Daniel Rezende','03/06/1989','thiagodanielrezende@aedu.com','Travessa Maria da Silva Alves','Casa Verde Alta','São Paulo','SP','(11) 3703-9299','1,500.00')
GO

INSERT INTO [dbo].[LOGIN]
           ([FUNC_CPF]
           ,[LOG_USUARIO]
           ,[LOG_SENHA]
           ,[LOG_DATACADASTRO]
           ,[LOG_PRIVILEGIO]
           ,[LOG_ATUALIZADOEM])
     VALUES
           ('479.458.138-60','adm','123','10/12/2010','ADMINISTRADOR')
GO
